#!/bin/bash

# Manual deployment script - copy and run each command on the remote server
# Server: 192.168.1.246
# User: root
# Password: 3646287

echo "=== Manual Deployment Commands ==="
echo "Connect to server: ssh root@192.168.1.246"
echo "Password: 3646287"
echo ""
echo "=== Step 1: Update System ==="
echo "apt update"
echo "apt install -y python3-pip python3-dev python3-venv mysql-server libmysqlclient-dev nginx supervisor"
echo ""
echo "=== Step 2: Create Application Directory ==="
echo "mkdir -p /opt/phishing-detector"
echo "cd /opt/phishing-detector"
echo ""
echo "=== Step 3: Create Virtual Environment ==="
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo ""
echo "=== Step 4: Install Dependencies ==="
echo "pip install --upgrade pip"
echo "pip install -r requirements.txt"
echo ""
echo "=== Step 5: Configure MySQL ==="
echo "systemctl start mysql"
echo "systemctl enable mysql"
echo "mysql -e 'CREATE DATABASE IF NOT EXISTS phishing_detector CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'"
echo "mysql -e \"CREATE USER IF NOT EXISTS 'phishing_user'@'localhost' IDENTIFIED BY 'phishing_password';\""
echo "mysql -e 'GRANT ALL PRIVILEGES ON phishing_detector.* TO '\\'phishing_user\\'@'\\'localhost\\';'"
echo "mysql -e 'FLUSH PRIVILEGES;'"
echo ""
echo "=== Step 6: Create Systemd Service ==="
echo "cat > /etc/systemd/system/phishing-detector.service << 'EOF'"
echo "[Unit]"
echo "Description=Phishing Detector API"
echo "After=network.target mysql.service"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=root"
echo "WorkingDirectory=/opt/phishing-detector"
echo "Environment=PATH=/opt/phishing-detector/venv/bin"
echo "ExecStart=/opt/phishing-detector/venv/bin/python -m app.api.routes"
echo "Restart=always"
echo "RestartSec=10"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""
echo "=== Step 7: Start Service ==="
echo "systemctl daemon-reload"
echo "systemctl enable phishing-detector"
echo "systemctl start phishing-detector"
echo ""
echo "=== Step 8: Configure Nginx ==="
echo "cat > /etc/nginx/sites-available/phishing-detector << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name _;"
echo ""
echo "    location / {"
echo "        proxy_pass http://127.0.0.1:5000;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo ""
echo "    location /static {"
echo "        alias /opt/phishing-detector/app/web/static;"
echo "        expires 1y;"
echo "        add_header Cache-Control \"public, immutable\";"
echo "    }"
echo "}"
echo "EOF"
echo ""
echo "ln -sf /etc/nginx/sites-available/phishing-detector /etc/nginx/sites-enabled/"
echo "rm -f /etc/nginx/sites-enabled/default"
echo "nginx -t"
echo "systemctl reload nginx"
echo ""
echo "=== Step 9: Check Status ==="
echo "systemctl status phishing-detector"
echo "systemctl status nginx"
echo ""
echo "=== Access Information ==="
echo "The application should be accessible at: http://192.168.1.246"
echo "API endpoints:"
echo "  - Health check: http://192.168.1.246/api/health"
echo "  - Detection: http://192.168.1.246/api/detect"
echo "  - Dashboard: http://192.168.1.246/dashboard"